permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: 王康
  email: beijingwangkang@hotmail.com
  link: http://catkang.github.io/
  weibo: 
  github: http://github.com/CatKang

# 站点信息
title: CatKang的博客 
description: Out of three sounds he frame, not a fourth sound, but a star
url: http://catkang.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://ww2.sinaimg.cn/thumbnail/69a9c739jw1exnxgdcu0dj20sg0iz40f.jpg
favicon: http://ww2.sinaimg.cn/thumbnail/69a9c739jw1exnxgdcu0dj20sg0iz40f.jpg

# disqus 设置
disqus:
  shortname: wangkang
